name: Test and create Docker image

on: [push, pull_request]

jobs:
  build:
    uses: HSLdevcom/transitdata-shared-workflows/.github/workflows/ci-cd-kotlin.yml@main
    with:
      uploadJarArtifact: true
      jarArtifactName: "transitlog-apc-sink.jar"
      jarArtifactPath: "build/libs/transitlog-apc-sink.jar"

  build-release-docker-image:
    needs: build
    runs-on: ubuntu-latest
    # Run only for tagged commits
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Download .jar file
        uses: actions/download-artifact@v4
        with:
          name: transitlog-apc-sink.jar
          path: build/libs
      - name: Build and publish release Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hsldevcom/transitlog-apc-sink
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          tag_semver: true
